//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Airport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если &apos;цель-улететь&apos; и &apos;денег-достаточно&apos; то &apos;можно улететь-да&apos;;
        ///Если &apos;можно улететь-да&apos; и &apos;ближе-Домодедово&apos; то &apos;аэропорт-Домодедово&apos;;
        ///Если &apos;можно улететь-да&apos; и &apos;ближе-Шереметьево&apos; то &apos;аэропорт-Шереметьево&apos;;
        ///Если &apos;аэропорт-Домодедово&apos; то &apos;билет продаст - Сергей&apos;, &apos;паспортный контроль - долгий&apos;;
        ///Если &apos;аэропорт-Шереметьево&apos; то &apos;билет продаст - Марина&apos;, &apos;паспортный контроль - быстрый&apos;;
        ///Если &apos;wifi - есть&apos; то &apos;пользуется wifi&apos;;
        ///Если &apos;аэропорт-Шереметьево&apos; то &apos;wifi - есть&apos;
        ///
        ///.
        /// </summary>
        internal static string knBase {
            get {
                return ResourceManager.GetString("knBase", resourceCulture);
            }
        }
    }
}
