//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Airport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если &apos;цель-улететь&apos; и &apos;денег-достаточно&apos; то &apos;можно улететь-да&apos;;
        ///Если &apos;можно улететь-да&apos; и &apos;ближе-Домодедово&apos; то &apos;аэропорт-Домодедово&apos;;
        ///Если &apos;можно улететь-да&apos; и &apos;ближе-Шереметьево&apos; то &apos;аэропорт-Шереметьево&apos;;
        ///Если &apos;аэропорт-Домодедово&apos; то &apos;билет продаст - Сергей&apos;, &apos;паспортный контроль - долгий&apos;;
        ///Если &apos;аэропорт-Шереметьево&apos; то &apos;билет продаст - Марина&apos;, &apos;паспортный контроль - быстрый&apos;;
        ///Если &apos;wifi - есть&apos; то &apos;пользуется wifi - да&apos;;
        ///Если &apos;аэропорт - Шереметьево&apos; то &apos;wifi - есть&apos;;
        ///Если (&apos;желание-купить&apos; и  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string knBase {
            get {
                return ResourceManager.GetString("knBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если &apos;выбор направления-Северная Америка&apos; то &apos;направление-Северная Америка&apos;;
        ///Если &apos;выбор направления-Европа&apos; то &apos;направление-Европа&apos;;
        ///Если &apos;выбор направления-Азия&apos; то &apos;направление-Азия&apos;;
        ///Если &apos;приоритет отеля-центр города&apos; то &apos;выбор отеля-центр города&apos;;
        ///Если &apos;приоритет отеля-окраина города&apos; то &apos;выбор отеля-окраина города&apos;;
        ///Если &apos;направление-Северная Америка&apos; и &apos;выбор страны-США&apos; то &apos;страна-США&apos;;
        ///Если &apos;направление-Северная Америка&apos; и &apos;выбор страны-Канада&apos; то &apos;страна-Канада&apos;;
        ///Если &apos;направление-Европа&apos;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TravelBase {
            get {
                return ResourceManager.GetString("TravelBase", resourceCulture);
            }
        }
    }
}
